service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

functions:
  api:
    handler: handler.graphql
    events: [ { http: 'ANY /graphql' }, { http: 'ANY /graphql/{proxy+}' } ]